### ISSUE TITLE
model selection during inference: model flag

### ISSUE THREAD

**Issue by Michal-Muszynski** [IBM/terratorch#121]
Terratorch config files used for model training should not have required any manual changes before running model inference.
There is a model flag in config files 
```
model:
  class_path: ...
  init_args:
    model_args:
      decoder: ...
      pretrained: true
```
That flag `pretrained: true` should be changed during inference automatically to avoid a situation in which end-users would not be sure about which model (pre-trained or fine-tuned) is used for running inference.
