### ISSUE TITLE
Fine-tuning with tubelet_size greater than 1

### ISSUE THREAD

**Issue by Foxigod** [IBM/terratorch#128]
@CarlosGomes98 
**Describe the issue**
I'm interested in fine-tuning a ViT model with the patch-embedding size set to something greater than 1 for the temporal dimension. To do this, I at least have to perform something similar to #118. When running after this change, I get an error like the following:
```
RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [80, 19200] but got: [80, 9216].
```
which seems to be sprouted from:
```
File "<PATH>/terratorch/terratorch/models/heads/classification_head.py", line 55, in forward
  x = self.head(x)
```

I believe the issue to be inconsistencies between the `TemporalViTEncoder`'s [`prepare_features_for_image_model`](https://github.com/IBM/terratorch/blob/41e2f84e3f7eb2f65f1dea7ad28f145aa040c4e8/terratorch/models/backbones/vit_encoder_decoder.py#L459-L488) function and the calculation of these ["num_chs" values](https://github.com/IBM/terratorch/blob/41e2f84e3f7eb2f65f1dea7ad28f145aa040c4e8/terratorch/models/backbones/vit_encoder_decoder.py#L205-L206) in the `TemporalViTEncoder`, however I'm not fully certain.

Can I ask someone to explain to me this transformation that is going on in `prepare_features_for_image_model`? What is its purpose, and do you have any references explaining why it is formulated the way it is?

**To Reproduce (optional, but appreciated)**
I'm performing a classification task with the following config entry with the aforementioned change like #118:
```
[...]
model:
  class_path: terratorch.tasks.ClassificationTask
  init_args:
    model_args:
      decoder: IdentityDecoder
      pretrained: true
      backbone: prithvi_vit_100
      backbone_pretrained_cfg_overlay:
        file: Prithvi_100M.pt
      backbone_patch_size: 3
      backbone_pretrain_img_size: 15
      backbone_tubelet_size: 3
[...]
```
