### ISSUE TITLE
Make the new datamodules more generic

### ISSUE THREAD

**Issue by WanjiruCate** [IBM/terratorch#399]
**Is your feature request related to a problem? Please describe.**
While using the new dataset specific datamodules like `Sen1Floods11NonGeoDataModule` , it is not possible to pass specific means and stds for another similar dataset i.e like a subset of it. 

The new datamodules only accept a `data_root` that is expected to be a folder with the specified names described in the datasets. 

**Describe the solution you'd like**
With the above problem it is not possible to scale easily for adding different datasets with different folder structures or different statistics.
It should be possible to override the default `means, stds, data_root files`of the specific datamodules in the tuning config.  

**Describe alternatives you've considered (optional)**
To continue using the generic datamodules as they allow the requested feature. 

**Additional context (optional)**
Is there any added advantage to use the specific dataset datamodules compared to the generic ones?

**Comment by Joao-L-S-Almeida** [comment]
Thanks @WanjiruCate.

**Comment by Joao-L-S-Almeida** [comment]
@paolofraccaro is talking to Blair about it.

**Comment by romeokienzler** [comment]
@WanjiruCate we had some discussions in the community call and think the cleanest solution is to use transforms - so we will work with you to either get an existing transform do what it should do or provide one - in both cases you'll be able to add the transform to the terratorch config and you are good to go

**Comment by romeokienzler** [comment]
so just sketching this out....

```
    train_transform:
      - class_path: albumentations.RandomCrop
        init_args:
          height: 224
          width: 224
      - class_path: albumentations.D4
      - class_path: ToTensorV2
      - class_path: torchvision.transforms.Normalize
          init_args:
                mean:
                  - 0.033349706741586264
                  - 0.05701185520536176
                  - 0.05889748132001316
                  - 0.2323245113436119
                  - 0.1972854853760658
                  - 0.11944914225186566
                std:
                  - 0.02269135568823774
                  - 0.026807560223070237
                  - 0.04004109844362779
                  - 0.07791732423672691
                  - 0.08708738838140137
                  - 0.07241979477437814
```
